steps:
- label: "Compile Ray"
  commands:
    - certutil -generateSSTFromWU roots.sst && certutil -addstore -f root roots.sst && rm roots.sst
    - ls
    - cd ray
    - . ./ci/travis/ci.sh init
    - . ./ci/travis/ci.sh build
