base_image: {{ env["RAY_IMAGE_ML_NIGHTLY_GPU"] | default("anyscale/ray-ml:nightly-py37-gpu") }}
env_vars: {"RAY_memory_usage_threshold_fraction": "0.9", "RAY_memory_monitor_interval_ms": "500"}

python:
  pip_packages:
    - boto3
    - pyarrow<7.0.0
  conda_packages: []

post_build_cmds:
  - pip3 uninstall -y ray && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install -U ray[default]
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
