base_image: {{ env["RAY_IMAGE_ML_NIGHTLY_GPU"] | default("anyscale/ray-ml:nightly-py37-gpu") }}
env_vars: {"LD_PRELOAD": "/usr/lib/x86_64-linux-gnu/libjemalloc.so","RAY_memory_usage_threshold_fraction": "0.9", "RAY_memory_monitor_interval_ms": "500"}

debian_packages:
- libjemalloc-dev

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip3 install tqdm || true
  - pip3 uninstall ray -y && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
